export type Ticket = {
  serialNumber?: string; // Optional because it will be generated by MongoDB
  name: string;
  platformName: string;
  Organization: string;
  subject: {
    title: string;
    description: string;
  };
  status: "New" | "Open" | "Hold" | "InProgress" | "Resolved" | "Closed"; // default: Open
  category: "bugs" | "Tech support" | "new feature" | "others";
  priority: "low" | "medium" | "high"; // default: medium
  type: "Support" | "Complaint" | "Feedback";
  days: number;
  createdAt?: string; // Auto-generated by Mongoose timestamps
  updatedAt?: string; // Auto-generated by Mongoose timestamps
};
